--- !ruby/object:Jumpstart::Configuration
application_name: Capital Viewer
business_name: Capital Viewer, LLC
domain: crecamp.com
support_email: support@crecamp.com
default_from_email: CRECamp <support@crecamp.com>
business_address: ''
background_job_processor: sidekiq
email_provider: sendgrid
personal_accounts: true
livereload: false
register_with_account: true
payment_processors:
- stripe
